
name: fretboard-segmentation
dependencies:
  - python=3.7
  - pip
  - pywavelets
  - scikit-image
  - pip:
    - numpy
    - matplotlib
    - opencv-python
    - scipy
    - scikit-learn
    
    
  
